favicon: /favicon.ico

mode: auto
language: zh-CN #en
banner:
  enable: true
  title: 倾倾倾风
  border: true
  cloud:
    enable: true
    color: 'white'
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# 头像
avatar:
  url: /images/avatar.jpg
  rounded: true
  opacity: 1

# 页面
pages:
  - name: 我的小伙伴们
    url: /links
    icon: icon-genderless-line
    color: dodgerblue

# 菜单
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - type: links
    #   path: /links/
    #   icon: icon-genderless-line
    #   color: dodgerblue
    #   count: 1
  custom:
    title: '主页'
    path: https://cins.cc
    icon: icon-disc-line

# colors:
# primary: '#6200ee'
# bg: '#F5F5F5'
# selection_bg: '#8e71c1' # 选取文字时的背景色
# 标签云中标签的起始色和结束色
# tag_start_color:
# tag_end_color:

tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  CSS: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'

social:
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://wpa.qq.com/msgrd?v=3&uin=578090135&site=qq&menu=yes
    icon: icon-qq-line
    color: '#12B7F5'
  - name: GitHub
    link: https://github.com/KinXpeng
    icon: icon-github-line
    color: '#dd734f'
  - name: E-Mail
    link: mailto:kinxpeng@163.com
    icon: icon-mail-line
    color: '#8E71C1'
  - name: 微博
    link: https://weibo.com/u/5123434857/home
    icon: icon-weibo-line
    color: '#E6162D'
  - name: 豆瓣
    # link: https://www.douban.com/people/yunyoujun/
    icon: icon-douban-line
    color: '#007722'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=116809620
    icon: icon-netease-cloud-music-line
    color: '#C10D0C'
  - name: 知乎
    link: https://www.zhihu.com/people/ling-feng-86-71
    icon: icon-zhihu-line
    color: '#0084FF'
  - name: 哔哩哔哩动画
    link: https://space.bilibili.com/19802757
    icon: icon-bilibili-line
    color: '#FF8EB3'
  - name: 微信公众号
    # link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
    icon: icon-wechat-2-line
    color: '#1AAD19'
  - name: Twitter
    link: https://twitter.com/KinXpeng
    icon: icon-twitter-line
    color: '#1da1f2'

# 公告
notice:
  enable: false
  content: 部分文章来自博主的掘金技术社区！(https://juejin.cn/user/3281399880616903)

# 背景图片
bg_image:
  enable: true
  url: https://kinxpeng.oss-cn-beijing.aliyuncs.com/image/cins-blog/2.jpeg?versionId=CAEQLRiBgMD.3tm7hBgiIDhkOGViMGFmMTIwNTQyZDU4MTJkNDljZDYyNzg0ZTIw
  dark: https://kinxpeng.oss-cn-beijing.aliyuncs.com/image/cins-blog/1.webp?versionId=CAEQLRiBgMDE59W7hBgiIDg4MWJkYTBhNDk0MTRkY2I5YWEyYjkwMWFjYWU1ZDE0
  blur: 5px # 设置背景模糊程度
  opacity: 0.6
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

sidebar:
  bg_image: https://kinxpeng.oss-cn-beijing.aliyuncs.com/image/cins-blog/2.jpeg?versionId=CAEQLRiBgMD.3tm7hBgiIDhkOGViMGFmMTIwNTQyZDU4MTJkNDljZDYyNzg0ZTIw
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

# 关闭 highlight
highlight:
  enable: true
# 启用 prism
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''
  light: /css/prism-tomorrow.min.css
  dark: /css/prismjs-dark.min.css

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

footer:
  since: 2022
  icon:
    name: icon-cloud-line
    animated: true
    color: '#0078E7'
  powered:
    enable: false
  live_time:
    enable: true
    prefix: 本博客已萌萌哒地运行
    suffix: (●'◡'●)
    start_time: '2022-05-01T00:00:00'

# 全国默哀日
mourn:
  enable: true
  days:
    - '4-4'

wordcloud:
  enable: true

# 打赏
reward:
  enable: true # 放在文章首部单独开启 reward: false
  icon: icon-hand-coin-line
  comment: Can you give me a reward?
  methods:
    - name: 支付宝
      path: https://kinxpeng.oss-cn-beijing.aliyuncs.com/image/paycode/541668755686_.pic.jpg
      color: '#00A3EE'
      icon: icon-alipay-line
    - name: 微信支付
      path: https://kinxpeng.oss-cn-beijing.aliyuncs.com/image/paycode/531668755685_.pic.jpg
      color: '#2DC100'
      icon: icon-wechat-pay-line
